### ISSUE TITLE
Would you tell me the key?

### ISSUE THREAD

**Issue by singlesparkshine** [jeuxdevilains/bookoflegalpossibilities#1]
In this issue from https://github.com/pozm/gdke/issues/10, according to your approach I got the key but failed to decompile codes using GDRE tools. Can you successfully decompile the game? If you  successed, would you tell me the key? The key i got is  86 71 42 49 52 51 10 06  D3 9F 4C 9E 91 8F 82 13 91 E2 B0 6A 80 D9 46 D6  93 FB 87 57 15 4C E8 49 bye IDA , set the breakpoint when calling set_decode_key

**Comment by jeuxdevilains** [comment]
Hello, @singlesparkshine ! You need [gdsdecomp ](https://github.com/bruvzg/gdsdecomp) to first extract the pck, then decompile the gde scripts using the key.

**Comment by singlesparkshine** [comment]
GDRE tools i used is the GUI version of gdsdecomp. The key i got is the same as you got?

**Comment by jeuxdevilains** [comment]
@singlesparkshine I can't really tell as it would probably be a breach of the EULA. With that said, I wonder if you succeeded after trying again? Don't forget to remove the spaces.

**Comment by singlesparkshine** [comment]
ok
